### ISSUE TITLE
Security Issue 

### ISSUE THREAD

**Issue by ousamabenyounes** [HRPersona/Backend#1]
Hi @ad3n 

Your parameters_prod.yml file has been compromised and your login/pwd are now visible on this this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

I recommand you also to use a gitignore file on the root of your Symfony project:
https://github.com/github/gitignore/blob/master/Symfony.gitignore
This will automatically ignore your parameters.yml file, your vendors ...

I also recommand you to plug your open source symfony project to sensioInsight...It's free and help you find all security, performance or quality issue on each commit

https://insight.sensiolabs.com/

Hope this will help you :)

**Comment by ad3n** [comment]
@ousamabenyounes : :+1: thanks very much, this repo is very premature repository, i will remove all credential as soon as possible
