### ISSUE TITLE
Apakah predis menjadi require

### ISSUE THREAD

**Issue by nuradiyana** [HRPersona/Backend#3]
Coba install sesuai dengan yang di README, saat jalankan command ```php bin/console doctrine:schema:update --force``` muncul error berikut

```
[Predis\Connection\ConnectionException]    
  Connection refused [tcp://localhost:6379]
```

Apakah memang harus menggunakan redis? apabila iya mungkin bisa ditambahkan di README,

OS pakai Linux Mint 18 dengan PHP 7.1.7-1+ubuntu16.04.1+deb.sury.org+1

**Comment by ad3n** [comment]
Yup gan... Required... Sorry belum diupdate
